### ISSUE TITLE
How to connect  Arduino to Azure IOT using Ethernet?

### ISSUE THREAD

**Issue by yuvaraj-gimco** [Azure/azure-iot-arduino#38] opened 2016-12-29 12:05 UTC
I have a requirement to connect Arduino to Azure IOT using Ethernet.  **Azure/Azure-iot-arduino** Package is not compatible with Ethernet.Can any one guide me,how to do this..?

**Comment by astaykov** [comment] 2017-01-02 10:45
This is duplicate of #28 

Currently there is no direct support for Ethernet.

**Comment by tameraw** [comment] 2017-03-31 22:43
Please see response in #28.

**Closed by tameraw** 2017-03-31 22:43 UTC
Labels: question
